

name: Continuous integration with Github Actions

on:
  push:
    branches: 
    - main 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Kogin to Docker Hub
 
      uses: docker/login-action@v3.0.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Application  JAR
      working-directory: ./workspaceSpring/rest-spring
      run: mvn clean package
      
    - name: Docker compose Build 
      working-directory: ./workspaceSpring
      run: docker compose up -d --build
      
    - name: Push to Docker Hub container registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-spring:latest ${{ secrets.DOCKER_USERNAME }}/rest-spring:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring:latest

 
