name: Integração contínua com GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Construir o arquivo JAR da aplicação
        working-directory: ./rest-spring
        run: mvn clean package

      - name: Construir com Docker Compose
        working-directory: ./rest-spring
        run: docker-compose up -d --build

      - name: Enviar para o registro de contêineres do Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/rest-spring:latest ${{ secrets.DOCKER_USERNAME }}/rest-spring:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring:latest
